spring.application.name=DailyMotionMiner

# Añadidas todas las líneas que aparecen en el vídeo, pueden no ser necesarias
server.port=8082
logging.level.aiss.dailymotionminer.controller=DEBUG
dailymotionminer.baseuri=https://partner.api.dailymotion.com

dailymotionminer.maxVideos = 10
dailymotionminer.maxComments = 2

videominer.uri=http://localhost:8080/videominer/channels